### ISSUE TITLE
toggle a boolean shorthand

### ISSUE THREAD

**Issue by Karyum** [WebAhead7/we-do-list#8]
instead of doing this https://github.com/WebAhead7/we-do-list/blob/main/src/data/script.js#L106-L110

you could do 

```javascript
      value.check = !value.check ;

```

**Comment by mjmajadly** [comment]
fixed:
function checkTask(id) {
  data.forEach((value) => {
    value.id == id ? (value.check = !value.check) : false;
  });
  updateDom(data);
  return data;
}
